# This workflow will do a clean installation of node dependencies, cache/restore them, build
# the source code and run tests across different versions of node. For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

env:
  GITHUB_ACTION: true

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

      - name: Checkout our own repository
        uses: actions/checkout@v5

      - name: Checkout Microsoft's fhir-codegen repository
        uses: actions/checkout@v5
        with:
          repository: microsoft/fhir-codegen
          path: .fhir-codegen

      - name: Locate all checked out repository roots
        run: |
          find . -name ".git" -type d
          find . -name ".fhir-codegen"
          tree . -L 3 || echo "tree command not found, skipping"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Build the code
        run: |
          npm run --silent clean
          npm ci
          npm run build --if-present

      - name: Run tests
        run: npm test
        continue-on-error: true
        env:
          FHIR_CACHE_DIR: ${{ github.workspace }}/.fhir
          
      - name: Figure out what happend
        env:
          FHIR_CACHE_DIR: ${{ github.workspace }}/.fhir
        run: |
          echo "===== FHIR_CACHE_DIR ====="
          echo "FHIR_CACHE_DIR=$FHIR_CACHE_DIR"
          find $FHIR_CACHE_DIR || echo "find command failed"
